### ISSUE TITLE
What should the logged out management interface look like?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/payments#105]
We're looking to trigger login on load of the management interface (at least by default - though this may not work on B2G - in which case we'll probably special case that scenario when we hit it)

In any case it would be useful to have a goal for what the management interface should look like when not logged in. The idea would be to avoid just having a big empty space.
- E.g. do we show the sidebar at all?
- Should we use the profile graphic?

**Comment by muffinresearch** [comment]
Another thought is, if we have a signout link (see #106) presumably automatic login wouldn't happen if you sign-out or would it?

**Comment by kumar303** [comment]
Currently, sign-in and sign-out state is not persisted between page loads. In other words, when you first load the page in a browser you will _always_ be signed out until you sign in.

**Comment by kumar303** [comment]
we could always stick a short lived refresh token in local storage if we wanted to (for persistent sign-in between page loads)

**Comment by brampitoyo** [comment]
The short answer is that the logged out management interface should look exactly like https://accounts.firefox.com/signin. But users who are already signed in to FxA will never need to see this page.

The long answer to this choice is three assumptions I had when designing FxA Payments:
1. The sign in page was to be a duplicate of the FxA Accounts sign in page, although the URL and entry point was always unclear to me. That is, where do you go to access the management interface? From your store account? From your Firefox preferences menu, under Sync?
2. Payments is just one of many services that FxA offers. Other services includes sync, sign in to websites, etc.
3. Ideally, every FxA services could be accessed from the same hub, using an interface that works the same way.

The implication of these assumptions:
- Payments management interface would look and feel similar to the FxA settings interface, and can be accessed from the same place.
- There’s no separated log in or log out. To log out, you also log out of accounts.firefox.com

Thoughts?

**Comment by muffinresearch** [comment]
@brampitoyo Sign-in is not so deeply integrated. E.g. we don't control the view that shows the login screen. That comes via the fxa client as a modal.

Due to how sign-in is currently setup it does have some independence. Because of this I think it makes sense to have a sign-out button. 

Assuming we can always get the fxa-login client to fire up as soon as the user is logged out - that will bring us fairly close to what the accounts page looks like except it will be our management interface with a modal fxa login on top of it.

**Comment by muffinresearch** [comment]
So I think we concluded the current direction is fine. Sign-out buttons are dealt with separately.
