### ISSUE TITLE
Can we have sign-in/sign-out graphics

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/payments#106]
For the management interface side-bar it would be nice to allow the user to sign-out explicitly.

Can we have some graphics for that?

This might be relevant to #105

**Comment by brampitoyo** [comment]
**Decision:** Have a menu item called “sign out” in sidebar. However, it should be clear that clicking it does _not_ lead you to a new page, unlike clicking all the other sidebar links. Maybe it could be styled like a button?

**Comment by brampitoyo** [comment]
What do you think about having the “sign out” button in the sidebar, like so?

![ux-management-sign-out-button](https://cloud.githubusercontent.com/assets/51007/9190821/12daf0f2-404e-11e5-9385-daaacae1a07d.png)

**Comment by muffinresearch** [comment]
It can be a button as it's an action. Looks good to me.

**Comment by muffinresearch** [comment]
This is implemented.
