### ISSUE TITLE
Management UX

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments#23]
Prepare a first pass of the UX flow for the management screens. This is where users will add payment methods, manage their subscriptions and other tasks.

Doing a first pass at this early so we can be sure we are on the right page.

**Comment by brampitoyo** [comment]
Starter feature list:
- Payment accounts: credit card, PayPal, etc.
  - Create
  - Read
  - Delete
- Receipts
  - Read
- Subscriptions
  - Read
  - Delete
- Account management
  - Read email
  - Update email – handled by Firefox Accounts?
  - Update password – handled by Firefox Accounts?
  - Delete

**Comment by brampitoyo** [comment]
UI mockups and flow (the flow doesn’t describe how the system will work in great detail, but gives you an idea of the style that Firefox Accounts Settings is going to follow).

![fxa payments - management wireframes flow](https://cloud.githubusercontent.com/assets/51007/7292256/4af6fffa-e9ee-11e4-9bca-6aa42a37345f.png)

**Comment by brampitoyo** [comment]
Updated UI mockups and flow to address use case of removing payment account and how it impacts existing subscription.

![fxa payments - management wireframes](https://cloud.githubusercontent.com/assets/51007/7364113/c040ad7e-edd6-11e4-899e-02b59e1ceca3.png)

And, as promised, below is a user flow diagram that details how each functionality within this page will work.

![fxa payments - management flow](https://cloud.githubusercontent.com/assets/51007/7364124/dbea65a6-edd6-11e4-8920-3474e1388901.png)

**Comment by andymckay** [comment]
Deleting an account is a good idea we hadn't considered. There's also only so much we can delete, we need to keep data around. I'm thinking we should do something like AMO does and after removing any subscriptions, blank out any personal information like email address, name etc. and anything that tied the user to the account, whilst keeping the actual transactions around for reporting and auditing.

**Comment by andymckay** [comment]
Receipts and Subscriptions looks like it could become a big page. And presumably we'll need to be able to paginate the receipts list?

**Comment by kumar303** [comment]
This is cool, Bram. What if instead of replacing the card in each orphaned subscription one by one they could do something like "replace all subscriptions that used this card with X" ? I suppose they may still want to review/replace one by one but if that list is long then they'd be tempted to click "Later" and that could result in money lost.

**Comment by andymckay** [comment]
Sorry if its not ready for commenting yet, but was excited to see this. Weeee!

**Comment by andymckay** [comment]
FYI, I think implementing changing email address is here: https://github.com/mozilla/fxa-content-server/issues/2335

**Comment by rfk** [comment]
> implementing changing email address is here

FYI we haven't scheduled this form implementation yet, if you need it lined up with a particular schedule on your end please comment in that bug.
