### ISSUE TITLE
Investigate Square Cash UI

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/payments#41]
https://cash.me/$wikipedia

**Comment by andymckay** [comment]
Any progress on this?

**Comment by brampitoyo** [comment]
Square Cash UI interests me chiefly for its form filling design pattern:
- It invites user to add credit card without the need to sign in or register
- When adding a new credit card from the buy/pay interface, the form expands
  ![square-cash-form-1](https://cloud.githubusercontent.com/assets/51007/7953229/57d01db8-0a16-11e5-8786-95febd20842a.gif)
- When adding a credit card from the management interface, the form looks very similar to our design
  ![square-cash-form-2](https://cloud.githubusercontent.com/assets/51007/7953463/3e12eac4-0a19-11e5-9ace-16bc375b3796.PNG)
- When the submit button returns an error, it’s ‘muted’ and cannot be selected
  ![square-cash-form-please-fix-errors](https://cloud.githubusercontent.com/assets/51007/7953488/b1d5ed62-0a19-11e5-8d95-93c20fb06984.PNG)
- The submit button doubles as a notification area; form field text is coloured red when invalid
  ![square-cash-form-invalid-zip](https://cloud.githubusercontent.com/assets/51007/7953496/ce020232-0a19-11e5-9d12-5eac19984426.PNG)

All in all, Square Cash buy/pay and management UI looks amazing, but does everything we already do.
