### ISSUE TITLE
Create initial credit card page

### ISSUE THREAD

**Issue by andymckay** [mozilla/payments#43]
User is logged, but has no card.

![screenshot 2015-05-05 09 27 34](https://cloud.githubusercontent.com/assets/74699/7477490/0444138a-f309-11e4-9085-ff1d35b67072.png)

In this scenario back button would not do anything so be removed.

**Comment by brampitoyo** [comment]
> In this scenario back button would not do anything

Yes. The back button would only appear when adding a new credit card on top of an existing card.
