### ISSUE TITLE
Display field errors and API errors.

### ISSUE THREAD

**Issue by andymckay** [mozilla/payments#45]
![screenshot 2015-05-05 09 34 35](https://cloud.githubusercontent.com/assets/74699/7477629/f774b3ac-f309-11e4-812d-18da70a78a9d.png)

Shows errors (this is based on an older mock).

Questions for @brampitoyo:
- There will be a delay as we ping braintree and attempt verification, should something happen then?
- Is there a difference between field and non-field errors?

**Comment by brampitoyo** [comment]
> There will be a delay as we ping braintree and attempt verification, should something happen then?

I forgot to account for this.

When clicked, the “Subscribe” button should change from blue (selectable) to gray (disabled) with a throbber animation. On failure, the button should appear disabled until the problematic value has been changed.

![payment-buy-error](https://cloud.githubusercontent.com/assets/51007/7488152/b229b034-f419-11e4-969a-b64a327c42de.gif)

(The animation isn’t completely accurate. The wrong field should be outlined red).

> Is there a difference between field and non-field errors?

If necessary, we can show the red error flag outside of the field, but I think the in-field error flags should be able to take care of everything we could think of?

When an error happens outside of the field or the process itself (for example, if your subscription fails to renew), we could send an email notification.
