### ISSUE TITLE
Share product information

### ISSUE THREAD

**Issue by andymckay** [mozilla/payments#57]
At the moment, multiple repositories need to know information about the products for sale. This includes, but is not limited to (i.e. please add in more things we need):
- product name
- localised versions of the product name
- product icon
- price
- subscription frequency
- terms and conditions for the product
- product-id in solitude
- seller-id in solitude
- and more...

There's two ideas I've had for storing this:
1) put it into solitude, the downside being there is a lot more information in this than we have currently in solitude
2) make a separate library and re-use that through all the projects, similar to marketplace-constants

I prefer option 2, what say you all?

**Comment by kumar303** [comment]
It's already [mostly in Solitude](https://github.com/mozilla/solitude/blob/master/lib/brains/models.py#L53) anyway so I don't really see a problem with keeping it there. We can make a pass-through API in payments-service for the UI to use similar to how we [pass-through the token API](http://payments-service.readthedocs.org/en/latest/topics/api.html#token-generator)

**Comment by muffinresearch** [comment]
I suppose for the latter it would mean you'd always need a release for changes. (If we had continuous deploy that would be a non-issue).

**Comment by kumar303** [comment]
I'd imagine in some cases the vendors may wish to keep product information private until it's announced which might mean keeping it in a library would be hard. If it were stored in a database and served up by an API then we could solve that. I don't think storing it in Solitude is a terrible idea but I understand the concerns.

**Comment by muffinresearch** [comment]
3rd option. Product service?

**Comment by andymckay** [comment]
I think a release for changes isn't a biggie as long as we can ensure that our cache busting actually works :)

The keeping things secret is an interesting option, I'd hate to build for that and every time we've tried this is been a pain since. For a Mozilla property there are sooo many clues as to whats happening. You could be watching the solitude repo, soltiude stage server, the mozilla concrete server. I would rather not try and do that and just say "hey our product config is open, you cool with that?" and not even try to hide it. That way leads to a hidden rabbit hole of doom.

**Comment by kumar303** [comment]
I think it's going to be really touchy PR-wise when Mozilla starts to sell things so we should be sensitive to it. Our code is currently all based around 'Mozilla Concrete' so I don't foresee any problems with the open source aspect of it but maybe you're right -- maybe it will become increasingly difficult to hide details of production data.
