### ISSUE TITLE
Send users an email receipt

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments#64]
Send users a nice email receipt.

This means figuring out what their address is.

Depends on mozilla/payments-service#35

**Comment by andymckay-limited-access** [comment]
Depends on mozilla/payments#72

**Comment by kumar303** [comment]
Depends on https://github.com/mozilla/payments-service/issues/58

**Comment by kumar303** [comment]
The email format is mocked up here: http://payments.readthedocs.org/en/latest/design/api/provider.html#subscription-created

**Comment by andymckay-limited-access** [comment]
This is done.
