### ISSUE TITLE
Cancelled subscription email

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments#77]
In http://payments.readthedocs.org/en/latest/design/api/provider.html#subscription-cancelled, it says "I think this is a job that can be accomplished using a really good subscription cancellation UI".

The problem is that a cancellation can happen when the user isn't there and there is no UI.

Examples:
- after a certain number of unsuccessful credit card retries, Braintree will cancel their subscription
- we can do it for users from the Braintree management interface for any sort of problem

We could theoretically say "if it was done by a user, don't send email" but I'm not sure yet if we can tell that. I think certainly there is enough cases where an email is warranted.

**Comment by andymckay-limited-access** [comment]
For mozilla/payments#64

**Comment by kumar303** [comment]
Subscription charge failures will be handled in https://github.com/mozilla/payments-service/issues/71

**Comment by kumar303** [comment]
In any case I can think of for cancelling a subscription, I think we should keep the subscription active up to the end date of their last payment. For example, if their last payment was for a period of June 1st - June 30th and the subscription is cancelled on June 15th then it should remain active until June 30th.

**Comment by kumar303** [comment]
Hey Bram, while waiting for the HTML mock up, I proposed a simple text version here: https://github.com/mozilla/payments-service/pull/74/files#diff-9696f21085a2fbaacd9e3fbc76d4ecc5R7 It's not specific about subscription end dates because we may need more data for that. See https://github.com/mozilla/payments-service/issues/75
