### ISSUE TITLE
Stand up the notification repo

### ISSUE THREAD

**Issue by andymckay** [mozilla/payments#8]
This is based on the assumption that for sending out notifications (via email or other tools) we'll use a seperate repo. In Marketplace payments, we use the marketplace itself for emailing out receipts (for example). The suggestion is to do this through a queue to another server.

**Comment by kumar303** [comment]
I don't think this is quite ready to work on yet as we don't fully understand notifications yet

**Comment by andymckay-limited-access** [comment]
Don't think this is relevant any more, closing.
