### ISSUE TITLE
Add or edit pay method

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments#84]
The purchase flow shows a way to edit cards.

**Comment by kumar303** [comment]
In the UI we can probably do something similar to how you can [click a link to trigger the payWithNewCard action](https://github.com/mozilla/payments-ui/blob/master/public/jsx/views/card-listing.jsx#L31). Instead it would need to pass the info from the user's `payment_methods` and could probably be received in a new if statement [within Purchase](https://github.com/mozilla/payments-ui/blob/master/public/jsx/views/purchase.jsx#L39) then passed to children for rendering/editing.

**Comment by andymckay** [comment]
I think we've actually got add already. So all that is left is the ability to edit cards. The UX flow shows a `manage` link in the bottom left that then alters the cards appearance and allows the editing of cards.

![screenshot 2015-06-29 09 20 43](https://cloud.githubusercontent.com/assets/74699/8412728/929081f2-1e40-11e5-9104-a113849c7735.png)

**Comment by andymckay** [comment]
After chatting with @brampitoyo we've decided to ditch this interface. All card deletion will happen in the management interface instead. We'll have links to the management interface in different places instead.
