### ISSUE TITLE
Stand up a management interface

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments#85]
Create the initial management interface.

**Comment by andymckay** [comment]
Its in flux, but it looks roughly like this:

![](http://payments.readthedocs.org/en/latest/_images/ux-management-wireframe.png)

**Comment by brampitoyo** [comment]
Updated the management interface with a few new features:
- Modal payment method UI (resolves mozilla/payments-ui#163, mozilla/payments-ui#164 and mozilla/payments-ui#165)
- Change subscription UI now uses the same modal UI as above, not a drop down menu (resolves mozilla/payments-ui#168)
- Add receipt page (resolves mozilla/payments-ui#167)
- When a payment method is removed, we no longer ask user to select a new account for each subscription. Instead:
  - If there’s one payment method left, we automatically set it for all subscriptions
  - If there’s no payment method left, or if there’s more than one, we don’t know which one to select, so we tell users to choose one later
  - We have also talked about doing away with this warning dialogue in favour of a simple `undo delete` button. I’m open to doing this design, too.

![fxa payments - management wireframes](https://cloud.githubusercontent.com/assets/51007/8539513/b11001ac-24d0-11e5-9631-a8d07a957af1.png)

**Comment by kumar303** [comment]
Awesome, this looks great! Can you update the section for this in the docs when you get a chance? http://payments.readthedocs.org/en/latest/design/ux.html#management

**Comment by andymckay** [comment]
I like that we are re-using common components across the screens, that makes a lot of sense to me.

Does anything happen on clicking a transaction? By any chance.... can we make it look similar to the details that are emailed?

And yes a pull request to update the docs is awesome.

**Comment by andymckay-limited-access** [comment]
This is pretty much stood up, now to finish off in #110.
